openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/auth/login:
    post:
      summary: ''
      operationId: postApiV1AuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: shields.renee@example.com
                  nullable: false
                password:
                  type: string
                  description: 'Must be at least 6  characters. Must not be greater than 18 characters.'
                  example: '/5jK%&s8z[-&G%#BqD$h'
                  nullable: false
              required:
                - email
                - password
      security: []
  /api/v1/user:
    post:
      summary: ''
      operationId: postApiV1User
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 6  characters. Must not be greater than 24 characters.'
                  example: ddgfvycohxrunvhslq
                  nullable: false
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: ludwig.crona@example.com
                  nullable: false
                password:
                  type: string
                  description: 'Must be at least 6  characters. Must not be greater than 18  characters.'
                  example: "#xan|'%Pl`-"
                  nullable: false
              required:
                - name
                - email
                - password
      security: []
    get:
      summary: ''
      operationId: getApiV1User
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/v1/user/{id}':
    put:
      summary: ''
      operationId: putApiV1UserId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    get:
      summary: ''
      operationId: getApiV1UserId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiV1UserId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the user.'
        example: beatae
        required: true
        schema:
          type: string
  /api/v1/category:
    post:
      summary: ''
      operationId: postApiV1Category
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Rem officiis sed tempore dolor nulla.'
                  nullable: true
              required:
                - name
      security: []
    get:
      summary: ''
      operationId: getApiV1Category
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/v1/category/{id}':
    get:
      summary: ''
      operationId: getApiV1CategoryId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiV1CategoryId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the category.'
        example: 15
        required: true
        schema:
          type: integer
  /api/v1/item:
    get:
      summary: ''
      operationId: getApiV1Item
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/v1/item/{id}':
    get:
      summary: ''
      operationId: getApiV1ItemId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiV1ItemId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the item.'
        example: quam
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
